name: boletera
description: "Novek ticket panel"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.2
  board_datetime_picker: ^1.4.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  easy_stepper: ^0.8.3
  equatable: ^2.0.5
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_bloc: ^8.1.3
  flutter_carousel_widget: ^2.2.0
  flutter_dotenv: ^5.1.0
  flutter_dropzone: ^3.0.7
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_stripe: ^10.1.0
  flutter_stripe_web: ^5.1.0
  get_it: ^7.6.6
  google_fonts: ^6.1.0
  graphql_flutter: ^5.1.2
  http: ^1.2.0
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  intl: ^0.18.1
  modal_progress_hud_nsn: ^0.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_calendar: ^24.1.45

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
