export 'package:boletera/src/ui/views/loader_view.dart';
export 'package:boletera/src/ui/views/auth/login_view.dart';
export 'package:boletera/src/ui/views/events/events_view.dart';
export 'package:boletera/src/ui/views/events/event_view2.dart';
export 'package:boletera/src/ui/views/auth/register_view.dart';
export 'package:boletera/src/ui/views/no_page_found_view.dart';
export 'package:boletera/src/ui/views/auth/change_pass_view.dart';
export 'package:boletera/src/ui/views/events/update_event_view.dart';
export 'package:boletera/src/ui/views/auth/recovery_pass_view.dart';